export const Awards_en = [
  {
    title: "Lungwa Programming Contest",
    description: "Honorable Mention",
    date: "2025-06-09",
    image: "/awards/lhpc.webp",
    id: "20250609-lhpc",
  },
  {
    title: "TQC+ Python Programming Certification",
    description: "Certified / Passed",
    date: "2025-06-13",
    image: "/awards/tqc.webp",
    id: "20250613-tqc",
  },
  {
    title: "APCS (Advanced Placement Computer Science)",
    description: "Concepts: Level 4・Implementation: Level 3",
    date: "2025-06-14",
    id: "20250614-apcs",
    image: "/awards/apcs.webp",
  },
  {
    title: "YTP (Young Turing Program)",
    description: "Finalist",
    date: "2025-08-23",
    image: "/awards/ytp.webp",
    id: "20250823-ytp",
  },
  {
    title: "FGJ (Faust Game Jam)",
    description: "Participant",
    date: "2025-09-14",
    id: "20250914-fgj",
    image: "/awards/fgj.webp",
  },
  {
    title: "Daydream Competition",
    description: "7th Place",
    date: "2025-09-28",
    image: "/awards/daydream.webp",
    id: "20250928-daydream",
  },
  {
    title: "NSTC Academic Conference",
    description: "Academic Presentation・Participation",
    date: "2025-10-12",
    image: "/awards/nstc.webp",
    id: "20251012-nstc",
  },
  {
    title: "AI City Node Innovation Competition",
    description: "Participant",
    date: "2025-11-06",
    id: "20251106-ai-node",
    image: "/awards/ai-node.webp",
  },
  {
    title: "2025 Taipei Autumn Codefest - Taipei Pass Microservices",
    description: "Participant",
    date: "2025-11-08",
    id: "20251108-tp-code",
    image: "/awards/tp-code.webp",
  },
  {
    title: "CPE (Collegiate Programming Examination)",
    description: "1 Problem Solved",
    date: "2025-12-09",
    image: "/awards/cpe.webp",
    id: "20251209-cpe",
  },
  {
    title: "2025 National AI Project Innovation Competition",
    description: "Honorable Mention",
    date: "2025-12-13",
    id: "20251213-ai-competition",
    image: "/awards/ai-competition.webp",
  },
];
